{"asctime": "2019-01-09T13:07:33Z+0800", "name": "root", "processName": "MainProcess", "filename": "<ipython-input-6-a1745ebc1fd0>", "funcName": "get_connect", "levelname": "INFO", "lineno": 11, "module": "<ipython-input-6-a1745ebc1fd0>", "threadName": "MainThread", "message": "HTTP response code = 200", "url": "https://www.ptt.cc/bbs/Food/index5.html", "time_use": 0.833556, "timestamp": "2019-01-09T13:07:33Z+0800"}
{"asctime": "2019-01-09T13:34:07Z+0800", "name": "root", "processName": "MainProcess", "filename": "<ipython-input-6-a1745ebc1fd0>", "funcName": "get_connect", "levelname": "INFO", "lineno": 11, "module": "<ipython-input-6-a1745ebc1fd0>", "threadName": "MainThread", "message": "HTTP response code = 522", "url": "https://www.ptt.cc/bbs/Food/index5.html", "time_use": 31.819015, "timestamp": "2019-01-09T13:34:07Z+0800"}
{"asctime": "2019-01-09T13:34:07Z+0800", "name": "root", "processName": "MainProcess", "filename": "<ipython-input-6-a1745ebc1fd0>", "funcName": "get_connect", "levelname": "ERROR", "lineno": 22, "module": "<ipython-input-6-a1745ebc1fd0>", "threadName": "MainThread", "message": "522 Server Error: Origin Connection Time-out for url: https://www.ptt.cc/bbs/Food/index5.html", "exc_info": "Traceback (most recent call last):\n  File \"<ipython-input-6-a1745ebc1fd0>\", line 13, in get_connect\n    logger.info(\"Connect error\",extra={\"url\" : url, \"http response\": resp.raise_for_status()})\n  File \"C:\\Users\\Big data\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\requests\\models.py\", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 522 Server Error: Origin Connection Time-out for url: https://www.ptt.cc/bbs/Food/index5.html", "timestamp": "2019-01-09T13:34:07Z+0800"}
